# Generated by Django 4.1.2 on 2022-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Укажите категорию', max_length=200),
        ),
    ]
