# Generated by Django 4.1.2 on 2022-10-16 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='Order',
        ),
    ]
