# Generated by Django 4.1.2 on 2022-10-16 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_additionalimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalImage',
        ),
    ]
