# Generated by Django 4.1.2 on 2022-10-16 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_delete_additionalimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='Почта')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор заказа', primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('n', 'Новая'), ('a', 'Принято в работу'), ('c', 'Выполнено')], default='n', help_text='Статус заказа', max_length=1)),
                ('customer_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.order')),
            ],
            options={
                'ordering': ['due_back'],
                'permissions': (('can_mark_returned', 'Установите статус заказа'),),
            },
        ),
    ]
