# Generated by Django 3.2.16 on 2022-10-17 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_customer_orderinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinstance',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studio.customer'),
        ),
    ]
