# Generated by Django 3.2.16 on 2022-10-17 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_alter_orderinstance_customer_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderinstance',
            options={'ordering': ['status'], 'permissions': (('can_mark_returned', 'Установите статус заказа'),)},
        ),
        migrations.RemoveField(
            model_name='orderinstance',
            name='due_back',
        ),
        migrations.AlterField(
            model_name='orderinstance',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
