# Generated by Django 3.2.16 on 2022-10-17 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_auto_20221017_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status'], 'permissions': (('can_mark_returned', 'Установите статус заказа'),)},
        ),
        migrations.AddField(
            model_name='order',
            name='customer_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('n', 'Новая'), ('a', 'Принято в работу'), ('c', 'Выполнено')], default='n', help_text='Статус заказа', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор заказа', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='OrderInstance',
        ),
    ]
