# Generated by Django 3.2.16 on 2022-10-17 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор заказа', primary_key=True, serialize=False),
        ),
    ]
